"""Start

Revision ID: a3fec4564817
Revises: 
Create Date: 2024-05-25 21:24:11.441508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fec4564817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_server_api_key'), 'edge_server', ['api_key'], unique=True)
    op.create_index(op.f('ix_edge_server_city'), 'edge_server', ['city'], unique=False)
    op.create_index(op.f('ix_edge_server_country'), 'edge_server', ['country'], unique=False)
    op.create_index(op.f('ix_edge_server_id'), 'edge_server', ['id'], unique=False)
    op.create_index(op.f('ix_edge_server_name'), 'edge_server', ['name'], unique=False)
    op.create_table('device',
    sa.Column('node_id', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=20), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('edge_server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edge_server_id'], ['edge_server.id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_device_api_key'), 'device', ['api_key'], unique=True)
    op.create_index(op.f('ix_device_node_id'), 'device', ['node_id'], unique=True)
    op.create_table('AccessLog',
    sa.Column('device_node_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_node_id'], ['device.node_id'], ),
    sa.PrimaryKeyConstraint('device_node_id', 'timestamp')
    )
    op.create_index(op.f('ix_AccessLog_device_node_id'), 'AccessLog', ['device_node_id'], unique=False)
    op.create_index(op.f('ix_AccessLog_timestamp'), 'AccessLog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_AccessLog_uid'), 'AccessLog', ['uid'], unique=False)
    op.create_table('UserAuth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('last_device_node_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['last_device_node_id'], ['device.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserAuth_authenticated'), 'UserAuth', ['authenticated'], unique=False)
    op.create_index(op.f('ix_UserAuth_id'), 'UserAuth', ['id'], unique=False)
    op.create_index(op.f('ix_UserAuth_uid'), 'UserAuth', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserAuth_uid'), table_name='UserAuth')
    op.drop_index(op.f('ix_UserAuth_id'), table_name='UserAuth')
    op.drop_index(op.f('ix_UserAuth_authenticated'), table_name='UserAuth')
    op.drop_table('UserAuth')
    op.drop_index(op.f('ix_AccessLog_uid'), table_name='AccessLog')
    op.drop_index(op.f('ix_AccessLog_timestamp'), table_name='AccessLog')
    op.drop_index(op.f('ix_AccessLog_device_node_id'), table_name='AccessLog')
    op.drop_table('AccessLog')
    op.drop_index(op.f('ix_device_node_id'), table_name='device')
    op.drop_index(op.f('ix_device_api_key'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_edge_server_name'), table_name='edge_server')
    op.drop_index(op.f('ix_edge_server_id'), table_name='edge_server')
    op.drop_index(op.f('ix_edge_server_country'), table_name='edge_server')
    op.drop_index(op.f('ix_edge_server_city'), table_name='edge_server')
    op.drop_index(op.f('ix_edge_server_api_key'), table_name='edge_server')
    op.drop_table('edge_server')
    # ### end Alembic commands ###
